@token = NotYet..
# A 404 will be returned if the page does not exist.
GET https://www.sgutranscripts.org/w/rest.php/v1/page/SGU_Episode_990
Content-Type: application/json
User-Agent: SGU Wiki Tooling (matthew.heguy@gmail.com)
# Authorization: Bearer {{token}}


### Show notes
GET https://www.theskepticsguide.org/podcasts/episode-990
User-Agent: SGU Wiki Tooling (matthew.heguy@gmail.com)
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
