from mwparserfromhell.string_mixin import StringMixIn
from mwparserfromhell.wikicode import Wikicode

__all__ = ["Parameter"]

class Parameter(StringMixIn):
    def __init__(self, name: str, value: str, showkey: bool) -> None: ...
    @property
    def name(self) -> Wikicode: ...
    @property
    def value(self) -> Wikicode: ...
    @property
    def showkey(self) -> bool: ...
    @name.setter
    def name(self, newval: str) -> None: ...
    @value.setter
    def value(self, newval: str) -> None: ...
    @showkey.setter
    def showkey(self, newval: str) -> None: ...
