name: Test Suite

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ruff:
    timeout-minutes: 5
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry pyright

      - uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: "3.11"

      - run: poetry install

      - name: Ruff lint check
        run: poetry run ruff check .

      - name: Ruff format check
        run: poetry run ruff format --check .

      - name: Run pyright
        run: pyright .
